config/routes.rb
Rails.application.routes.draw do
  root to: "owners#index"

  resources :owners do
    resources :machines, only: [:index]
  end

  resources :machines, only: [:show]

  resources :snacks, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
  validates_presence_of :location

  belongs_to :owner
  has_many :machine_snacks
  has_many :snacks, through: :machine_snacks
end

app/models/machine_snack.rb
class MachineSnack < ApplicationRecord

  belongs_to :machine
  belongs_to :snack
end

app/models/owner.rb
class Owner < ApplicationRecord
  validates_presence_of :name

  has_many :machines
end

app/models/snack.rb
class Snack < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :price

  has_many :machine_snacks
  has_many :machines, through: :machine_snacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    @owner = Owner.find(params[:owner_id])
  end

  def show
    @machine = Machine.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

  def show
    @snack = Snack.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/index.html.erb
<h1><%= @owner.name %> Vending Machines</h1>

<% @owner.machines.each do |machine| %>
  <p><%= link_to machine.location, machine_path(machine)%></p>
<% end %>

app/views/machines/show.html.erb
<h1><%= @machine.location %> Vending Machine</h1>
<p>Average Price: <%= number_to_currency(@machine.snacks.average(:price)) %></p>
<% @machine.snacks.each do |snack| %>
  <p><%= snack.title %></p>
  <p><%= number_to_currency(snack.price) %></p>
  <% end %>

app/views/owners/index.html.erb
<h1>Vending Machine Owners</h1>

<ul>
  <% @owners.each do |owner| %>
    <li><%= owner.name %></li>
  <% end %>
</ul>

app/views/snacks/show.html.erb
<h1><%= @snack.title%></h1>
<p>Snack Price: <%= number_to_currency(@snack.price) %></p>
<% @snack.machines.each do |machine| %>
<p><%= machine.location %></p>
<p><%= number_to_currency(machine.snacks.average(:price)) %></p>
<p><%= machine.snacks.count %></p>
<% end %>